### ISSUE TITLE
setup pin code leads to incorrect code generation

### ISSUE THREAD

**Issue by zverev-iv** [akopachov/flipper-zero_authenticator#122] opened 2023-04-07 09:30 UTC
Case:  I Have QR code with all info.
1. I added this TOTP in two apps (andOTP android, but I think you can use anything else) and in flipper TOTP.
2. They show the same code. Codes works.
3. Then I set up pin code on flipper totp (using telnet) and close the app
4. After flipper TOTP restart it shows different codes from andOTP and this code isn't usable

Firmware unlshd-042e

**Comment by akopachov** [comment] 2023-04-07 09:40
Could you please provide Authenticator version and your Flipper's firmware and its version?

**Comment by zverev-iv** [comment] 2023-04-07 09:52
update information unlshd-042e- https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-042

**Comment by akopachov** [comment] 2023-04-07 10:09
Here is what I did to test this on my Flipper:
1. Grab new secret [here](https://www.verifyr.com/en/otp/check#totp)
2. Added it to the app
3. Made sure generated code is correct
4. Removed PIN via `totp pin remove`
5. Made sure generated code is correct
6. Restarted app
7. Made sure generated code is correct
8. Setup new PIN via `totp pin set`
9. Made sure generated code is correct
10. Restarted app
11. Made sure generated code is correct

So far was not able to reproduce the issue.

Do you remember if any unusual things happened? Or maybe something what is not covered by the test steps I did above? Can you try to reproduce this issue using test website I provided above?

**Comment by akopachov** [comment] 2023-04-07 10:15
In any case, logged #123 to make sure there is backup

**Comment by akopachov** [comment] 2023-04-11 12:23
> Do you remember if any unusual things happened? Or maybe something what is not covered by the test steps I did above? Can you try to reproduce this issue using test website I provided above?

Is there any chance to try it?

**Comment by akopachov** [comment] 2023-04-12 15:08
Closing as I was not able to reproduce this issue, author is not responding and the necessary improvements to take a backup before setting\removing PIN is added.

**Closed by akopachov** 2023-04-12 15:08 UTC
Labels: question

**Comment by zverev-iv** [comment] 2023-04-13 09:11
Hi! Sorry for late answer.
I can't reproduce it.
I tried many times. actually happened **twice**, but perhaps this is due to the time shift in rtc (for example, it leads to a firmware update or something else)
